catalog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url

from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('libros/', views.LibroListView.as_view(), name='libros'),
	path('libro/<int:pk>/', views.LibroDetailView.as_view(), name='libro-detalle'),
	path('autores/', views.AutorListView.as_view(), name='autores'),
	path('autor/<int:pk>/', views.AutorDetailView.as_view(), name='autor-detalle'),   
]

# URLConf para listr los libros prestados por usuario y en general.
urlpatterns += [
    path('mislibros/', views.LibrosPrestadosPorUsuarioListView.as_view(), name='mis-prestamos'),
    path('prestamos/', views.LibrosPrestadosListView.as_view(), name='prestamos'),
]

# URLConf para renovar (fecha_devolucion) un libro.
urlpatterns += [
    path('libro/<uuid:pk>/renovar/', views.RenovarLibroBibliotecario, name='renovar-libro-bibliotecario'),
]

# URLConf para crear, actualizar y eliminar autores
urlpatterns += [
    path('autor/create/', views.AutorCreate.as_view(), name='autor_create'),
    path('autor/<int:pk>/update/', views.AutorUpdate.as_view(), name='autor_update'),
    path('autor/<int:pk>/delete/', views.AutorDelete.as_view(), name='autor_delete'),
]

# Add URLConf to create, update, and delete books
urlpatterns += [
    path('libro/create/', views.LibroCreate.as_view(), name='libro_create'),
    path('libro/<int:pk>/update/', views.LibroUpdate.as_view(), name='libro_update'),
    path('libro/<int:pk>/delete/', views.LibroDelete.as_view(), name='libro_delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include

# Agrega mapeo de URL para redirigir la URL base a la aplicación
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Use static() para agregar mapeo de URL para servir archivos estáticos durante el desarrollo
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models

# Utilizado para generar URL invirtiendo los patrones de URL
from django.urls import reverse

# Create your models here.

class MyModelName(models.Model):
	"""	Una clase típica definiendo un modelo, derivado desde la clase Model. """

	# Campos
	my_field_name = models.CharField(max_length=20, help_text="Enter field documentation.")

	# Metadata
	class Meta: 
		ordering = ["-my_field_name"]

	# Métodos
	def get_absolute_url(self):
		""" Devuelve la url para acceder a una instancia particular de MyModelName. """
		return reverse('model-detail-view', args=[str(self.id)])

	def __str__(self):
		""" Cadena para representar el objeto MyModelName (en el sitio de Admin, etc.) """
		return self.field_name

class Autor(models.Model):
	""" Modelo que representa un autor """
	nombre = models.CharField(max_length=100)
	apellido = models.CharField(max_length=100)
	fecha_nacimiento = models.DateField(null=True, blank=True)
	fecha_fallecimiento = models.DateField('Fallecimiento', null=True, blank=True)

	def get_absolute_url(self):
		""" Retorna la url para acceder a una instancia particular de un autor. """
		return reverse('autor-detalle', args=[str(self.id)])

	def __str__(self):
		""" String para representar el Objeto Modelo """
		return '%s, %s' % (self.apellido, self.nombre)

class Genero(models.Model):
	""" Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.). """
	name = models.CharField(max_length=200, help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.).")

	def __str__(self):
		"""	Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración) """
		return self.name

class Idioma(models.Model):
	"""Modelo que representa un idioma (por ejemplo, inglés, francés, japonés, etc.)"""
	idioma = models.CharField(max_length=200, help_text="Ingrese el idioma natural del libro (por ejemplo, inglés, francés, japonés, etc.).")

	def __str__(self):
		"""String for representing the Model object (in Admin site etc.)"""
		return self.idioma

class Libro(models.Model):
	""" Modelo que representa un libro (pero no un Ejemplar específico)."""
	titulo = models.CharField(max_length=200)

	# ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
	autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
	resumen = models.TextField(max_length=1000, help_text="Ingrese un breve resumen del libro.")
	isbn = models.CharField('ISBN',max_length=13, help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn" target="_blank">ISBN number</a>')
	# ManyToManyField, porque un género puede contener muchos libros y un libro puede cubrir varios géneros.
	genero = models.ManyToManyField('Genero', help_text="Seleccione un genero para este libro.")
	idioma = models.ForeignKey('Idioma', on_delete=models.SET_NULL, null=True)

	def display_generos(self):
		""" Crea una cadena con los Géneros al que pertenece un Libro. Esto es necesario para mostrar en Admin. """
		return ', '.join([ genero.name for genero in self.genero.all()[:3] ])
	
	""" Crea una discripcion corta para los Géneros para mostrar como cabecera de tabla en Admin. """
	display_generos.short_description = 'Géneros'

	def __str__(self):
		""" String que representa al objeto Libro """
		return self.titulo

	def get_absolute_url(self):
		""" Devuelve el URL a una instancia particular de Libro """
		return reverse('libro-detalle', args=[str(self.id)])

# Requerida para las instancias de libros únicos
import uuid
from datetime import date
# Requerido para asignar al usuario como prestatario.
from django.contrib.auth.models import User

class LibroCopia(models.Model):
	"""	Modelo que representa una copia específica de un libro (i.e. que puede ser prestado por la biblioteca). """
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca.")
	libro = models.ForeignKey('Libro', on_delete=models.SET_NULL, null=True) 
	imprenta = models.CharField(max_length=200)
	fecha_devolucion = models.DateField(null=True, blank=True)
	prestatario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

	@property
	def is_atrasado(self):
		if self.fecha_devolucion and date.today() > self.fecha_devolucion:
			return True
		return False

	LOAN_STATUS = (
	    ('m', 'Maintenance'),	# mantenimiento
	    ('o', 'On loan'),		# en prestamo
	    ('a', 'Available'),		# disponible
	    ('r', 'Reserved'),		# reservado
	)

	status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Disponibilidad del libro.')

	class Meta:
		ordering = ["fecha_devolucion"]
		permissions = (("puede_marcar_devuelto", "Establecer libro como devuelto"),)

	def __str__(self):
		""" String para representar el Objeto del Modelo """
		return '%s (%s)' % (self.id, self.libro.titulo)
		# return '{0} ({1})'.format(self.id,self.libro.titulo) 
		# return f'{self.id} ({self.libro.titulo})'

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime
    
class RenovarLibroForm(forms.Form):
	renovar_fecha = forms.DateField(help_text="Inrese una fecha entre hoy y 4 semanas siguientes (por defecto son 3).")

	def clean_renovar_fecha_devolucion(self):
		data = self.cleaned_data['renovar_fecha']

		# Verificamos que la fecha no este en el pasado.
		if data < datetime.date.today():
			raise ValidationError(_('Fecha no válida - renovación en el pasado'))

		# Verificamos que la fecha este en el rango que el bibliotecario puede cambiar (+4 semanas).
		if data > datetime.date.today() + datetime.timedelta(weeks=4):
			raise ValidationError(_('Fecha no válida - renovación con más de 4 semanas de anticipación'))

		# Recuerde devolver siempre los datos limpios.
		return data

from django.forms import ModelForm
from .models import LibroCopia

class RenovarLibroModelForm(ModelForm):
	def clean_fecha_devolucion(self):
		data = self.cleaned_data['fecha_devolucion']

		# Verifica si la fecha_devolucion no está pasada.
		if data < datetime.date.today():
			raise ValidationError(_('Fecha no válida - renovación en el pasado.'))

		# Verifica si la fecha_devolucion esta en el rango permitido, maximo 4 semanas.
		if data > datetime.date.today() + datetime.timedelta(weeks=4):
			raise ValidationError(_('Fecha no válida - renovación maximo por 4 semanas.'))

		# Remember to always return the cleaned data.
		return data
	class Meta:
		model = LibroCopia
		fields = ['fecha_devolucion',]
		labels = { 'fecha_devolucion': _('Nueva fecha de devolcuon'), }
		help_texts = { 'fecha_devolucion': _('Inrese una fecha entre hoy y 4 semanas siguientes (por defecto son 3).'), }

catalog/views.py
from django.shortcuts import render

from .models import Libro, Autor, LibroCopia, Genero

# Create your views here.

def home(request):
	"""	Función vista para la página inicio del sitio. """

	# Genera contadores de algunos de los objetos principales
	num_libros = Libro.objects.all().count()
	num_copias = LibroCopia.objects.all().count()

	# Libros disponibles (status = 'a')
	num_copias_disponibles = LibroCopia.objects.filter(status__exact='a').count()

	num_autores = Autor.objects.count()  # El 'all()' esta implícito por defecto.

	num_generos = Genero.objects.count()

	# Número de visitas a esta vista, contadas en la variable de sesión.
	num_visitas = request.session.get('num_visitas', 0)
	request.session['num_visitas'] = num_visitas + 1

	# Renderiza la plantilla HTML home.html con los datos en la variable contexto
	return render(
		request,
		'home.html',
		context={'num_libros':num_libros,'num_generos':num_generos,'num_copias':num_copias,'num_copias_disponibles':num_copias_disponibles,'num_autores':num_autores,'num_visitas':num_visitas}, # num_visitas anexado
	)

# Listas genéricas y vistas de detalle
from django.views import generic

class LibroListView(generic.ListView):
	model = Libro
	paginate_by = 3

class LibroDetailView(generic.DetailView):
    model = Libro

class AutorListView(generic.ListView):
	model = Autor
	paginate_by = 3

class AutorDetailView(generic.DetailView):
	model = Autor


from django.contrib.auth.mixins import LoginRequiredMixin

class LibrosPrestadosPorUsuarioListView(LoginRequiredMixin, generic.ListView):
	"""	Vista genérica basada en clases que muestra los libros prestados al usuario actual. """
	model = LibroCopia
	template_name ='catalog/copialibro_lista_prestados_user.html'
	paginate_by = 3

	def get_queryset(self):
		return LibroCopia.objects.filter(prestatario=self.request.user).filter(status__exact='o').order_by('fecha_devolucion')

from django.contrib.auth.mixins import PermissionRequiredMixin

class LibrosPrestadosListView(PermissionRequiredMixin, generic.ListView):
	"""	Vista genérica basada en clases que muestra todos los libros prestados. """
	permission_required = 'catalog.puede_marcar_devuelto'

	model = LibroCopia
	template_name ='catalog/copialibro_lista_prestados.html'
	paginate_by = 3

	def get_queryset(self):
		return LibroCopia.objects.filter(status__exact='o').order_by('fecha_devolucion')

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
# from django.core.urlresolvers import reverse
from django.urls import reverse
# datetime es una biblioteca de Python para manipular fechas y horas. 
import datetime
from .forms import RenovarLibroForm, RenovarLibroModelForm
from django.contrib.auth.decorators import permission_required

@permission_required('catalog.puede_marcar_devuelto')
def RenovarLibroBibliotecario(request, pk):
	# get_object_or_404() Devuelve un objeto especificado de un modelo en función de su valor de clave principal
	# y genera una Http404excepción (no encontrada) si el registro no existe. 
	libro_copia=get_object_or_404(LibroCopia, pk = pk)

	# Si se trata de una solicitud POST, procesa los datos del formulario
	if request.method == 'POST':
		# Crea una instancia de formulario y compléta con datos de la solicitud
		#form = RenovarLibroForm(request.POST)
		form = RenovarLibroModelForm(request.POST)
		# Verifiqua si el formulario es válido
		if form.is_valid():
			# Procesa los datos en form.cleaned_data según sea necesario (aquí solo lo escribimos en el campo modelo fecha_devolucion)
			libro_copia.fecha_devolucion = form.cleaned_data['fecha_devolucion']
			libro_copia.save()

			# HttpResponseRedirect crea una redirección a una URL especificada.
			return HttpResponseRedirect(reverse('prestamos') )

	# Si es un GET (o cualquier otro método), crea el formulario predeterminado.
	else:
		renovar_fecha_por_defecto = datetime.date.today() + datetime.timedelta(weeks=3)
		#form = RenovarLibroForm(initial={'renovar_fecha': renovar_fecha_por_defecto,})
		form = RenovarLibroModelForm(initial={'fecha_devolucion': renovar_fecha_por_defecto,})

	return render(request, 'catalog/libro_renovar_bibliotecario.html', {'form': form, 'librocopia':libro_copia})

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Autor

#@permission_required('catalog.puede_marcar_devuelto')
class AutorCreate(PermissionRequiredMixin, CreateView):
	# Se necesita el permiso "catalog.puede_marcar_devuelto" para poder acceder a la vista
	permission_required = 'catalog.puede_marcar_devuelto'
	model = Autor
	fields = '__all__'
	initial={'fecha_fallecimiento':'05/01/2018',}

class AutorUpdate(PermissionRequiredMixin, UpdateView):
	# Se necesita el permiso "catalog.puede_marcar_devuelto" para poder acceder a la vista
	permission_required = 'catalog.puede_marcar_devuelto'
	model = Autor
	fields = ['nombre','apellido','fecha_nacimiento','fecha_fallecimiento']

class AutorDelete(PermissionRequiredMixin, DeleteView):
	# Se necesita el permiso "catalog.puede_marcar_devuelto" para poder acceder a la vista
	permission_required = 'catalog.puede_marcar_devuelto'
	model = Autor
	success_url = reverse_lazy('autores')

class LibroCreate(PermissionRequiredMixin, CreateView):
	# Se necesita el permiso "catalog.puede_marcar_devuelto" para poder acceder a la vista
	permission_required = 'catalog.puede_marcar_devuelto'
	model = Libro
	fields = '__all__'

class LibroUpdate(PermissionRequiredMixin, UpdateView):
	# Se necesita el permiso "catalog.puede_marcar_devuelto" para poder acceder a la vista
	permission_required = 'catalog.puede_marcar_devuelto'
	model = Libro
	#fields = ['nombre','apellido','fecha_nacimiento','fecha_fallecimiento']
	fields = '__all__'

class LibroDelete(PermissionRequiredMixin, DeleteView):
	# Se necesita el permiso "catalog.puede_marcar_devuelto" para poder acceder a la vista
	permission_required = 'catalog.puede_marcar_devuelto'
	model = Libro
	success_url = reverse_lazy('libros')

catalog/templates/catalog/autor_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Eliminar Autor</h1>

<p>¿Estás seguro de que deseas eliminar al autor: {{ author }}?</p>

<form action="" method="POST">
	{% csrf_token %}
	<input type="submit" action="" value="Si, eliminar." />
</form>

{% endblock %}

catalog/templates/catalog/autor_detail.html
{% extends "base.html" %}

{% block content %}

	<h2>{{ autor.nombre }} {{ autor.apellido }}</h2>

	<p><strong>Fecha Nacimiento:</strong> {{ autor.fecha_nacimiento }}</p>
	<p><strong>Fecha Fallecimiento:</strong> {{ autor.fecha_fallecimiento }}</p>

	<div style="margin-left:20px;margin-top:20px">
		<h4>Libros escritos:</h4>

		<!-- El método _set() es "automágicamente" creado por Django para devolver el conjunto de registros de autorCopia asociado con un autor en particular -->
		{% for libro in autor.libro_set.all %}
			<hr>
			<p><strong>Titulo:</strong> <a href="{{ libro.get_absolute_url }}">{{ libro.titulo }}</a>, <em>{{ libro.resumen }}.</em></p>
		{% endfor %}
	</div>
{% endblock %}

catalog/templates/catalog/autor_form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">

	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/autor_list.html
{% extends "base.html" %}

{% block content %}
	<h1>Lista de Autores</h1>

	{% if autor_list %}
		<ul>

			{% for autor in autor_list %}
				<li>
					<a href="{{ autor.get_absolute_url }}">{{ autor.apellido }}, {{ autor.nombre }} ({{autor.fecha_nacimiento}})</a>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No hay libros en la biblioteca.</p>
	{% endif %}
{% endblock %}

catalog/templates/catalog/copialibro_lista_prestados.html
{% extends "base.html" %}

{% block content %}
    <h1>Libros Prestados</h1>

    {% if librocopia_list %}
    <ul>

      {% for librocopia in librocopia_list %} 
      <li>
      	<p><a href="{% url 'libro-detalle' librocopia.libro.pk %}">{{librocopia.libro.titulo}}</a></p>
        <p class="{% if librocopia.is_atrasado %}text-danger{% endif %}">Fecha de devolucion: {{ librocopia.fecha_devolucion }}</p>
  		  <p>Prestado a: <strong>{{ librocopia.prestatario }}</strong></p> 
        {% if perms.catalog.puede_marcar_devuelto %}
          <p><a href="{% url 'renovar-libro-bibliotecario' librocopia.id %}">Renovar fecha de devolucion?</a></p>
        {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No existen libros prestados.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/copialibro_lista_prestados_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Mis Prestamos</h1>

    {% if librocopia_list %}
    <ul>

      {% for librocopia in librocopia_list %} 
      <li class="{% if librocopia.is_atrasado %}text-danger{% endif %}">
        <a href="{% url 'libro-detalle' librocopia.libro.pk %}">{{librocopia.libro.titulo}}</a> ({{ librocopia.fecha_devolucion }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No tiene libros prestados.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/libro_detail.html
{% extends "base.html" %}

{% block content %}

	<h1>Titulo: {{ libro.titulo }}</h1>

	<p><strong>Autor:</strong> <a href="{% url 'autor-detalle' libro.autor.pk %}">{{ libro.autor }}</a></p>
	<p><strong>Resumen:</strong> {{ libro.resumen }}</p>
	<p><strong>ISBN:</strong> {{ libro.isbn }}</p> 
	<p><strong>Idioma:</strong> {{ libro.idioma }}</p>  
	<p><strong>Genero:</strong> 
		{% for genero in libro.genero.all %} 
			{{ genero }}
			{% if not forloop.last %}, 
			{% endif %}
		{% endfor %}
	</p>  

	<div style="margin-left:20px;margin-top:20px">
		<h4>Copias</h4>

		<!-- El método _set() es "automágicamente" creado por Django para devolver el conjunto de registros de LibroCopia asociado con un Libro en particular -->
		{% for copia in libro.librocopia_set.all %}
			<hr>
			<p class="
				{% if copia.status == 'a' %}text-success
				{% elif copia.status == 'm' %}text-danger
				{% else %}text-warning{% endif %}">
				{{ copia.get_status_display }}
			</p>
			{% if copia.status != 'a' %}
				<p><strong>Fecha de devolucion:</strong> {{copia.fecha_devolucion}}</p>
			{% endif %}
			<p><strong>Imprenta:</strong> {{copia.imprenta}}</p>
			<p class="text-muted"><strong>Id:</strong> {{copia.id}}</p>
		{% endfor %}
	</div>
{% endblock %}

catalog/templates/catalog/libro_form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">

	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/libro_list.html
{% extends "base.html" %}

{% block content %}
	<h1>Lista de Libros</h1>

	{% if libro_list %}
		<ul>

			{% for libro in libro_list %}
				<li>
					<a href="{{ libro.get_absolute_url }}">{{ libro.titulo }} ({{libro.autor}})</a> 
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No hay libros en la biblioteca.</p>
	{% endif %}
{% endblock %}

catalog/templates/catalog/libro_renovar_bibliotecario.html
{% extends "base.html" %}
{% block content %}

<h1>Renovar: {{librocopia.libro.titulo}}</h1>
<p><strong>Prestatario:</strong> {{librocopia.prestatario}}</p>
<p {% if librocopia.is_atrasado %} class="text-danger"{% endif %}><strong>Fecha de devolucion:</strong> {{librocopia.fecha_devolucion}}</p>

<form action="" method="post">
	{% csrf_token %}
	<table>
		{{ form.as_p }}
	</table>
	<input type="submit" value="Submit" />
</form>

{% endblock %}